

services:
  # Base de Datos
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: examenad
    volumes:
      - ./script_ex_2B.txt:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3316:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servidores Flask
  server1:
    build: ./api
    container_name: flask_server1
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=examenad
      - SERVER_ID=server1
    depends_on:
      db:
        condition: service_healthy

  server2:
    build: ./api
    container_name: flask_server2
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=examenad
      - SERVER_ID=server2
    depends_on:
      db:
        condition: service_healthy

  # Balanceador de Carga
  nginx:
    image: nginx:alpine
    container_name: load_balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2

  # Divide los datos del nginx
  preparador:
    build: ./mapreduce
    container_name: preparador
    command: python preparador.py
    volumes:
      - mr_data:/app/splits
    depends_on:
      - nginx

  # Procesa cada parte en paralelo
  mapper1:
    build: ./mapreduce
    container_name: mapper1
    command: python mapper.py splits/part_01.txt
    volumes:
      - mr_data:/app/splits
    depends_on:
      preparador:
        condition: service_completed_successfully

  mapper2:
    build: ./mapreduce
    container_name: mapper2
    command: python mapper.py splits/part_02.txt
    volumes:
      - mr_data:/app/splits
    depends_on:
      preparador:
        condition: service_completed_successfully

  mapper3:
    build: ./mapreduce
    container_name: mapper3
    command: python mapper.py splits/part_03.txt
    volumes:
      - mr_data:/app/splits
    depends_on:
      preparador:
        condition: service_completed_successfully

  # Combina y procesa los datos para mostrar los resultados
  reducer:
    build: ./mapreduce
    container_name: reducer
    command: python reducer.py
    volumes:
      - mr_data:/app/splits
    depends_on:
      mapper1:
        condition: service_completed_successfully
      mapper2:
        condition: service_completed_successfully
      mapper3:
        condition: service_completed_successfully

volumes:
  mr_data:
